spring:
  application:
    name: user
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/ms-user-ms}
    username: ${SPRING_DATASOURCE_USERNAME:postgres-user}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:amqp://localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

app:
  rabbitmq:
    queues:
      email-notification: ${APP_RABBITMQ_QUEUES_EMAILNOTIFICATION:email-queue}
      simulated-delay: ${APP_RABBITMQ_QUEUES_SIMULATEDDELAY:simulated-delay-queue}
