spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_email_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest
    virtual-host: /

  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: efroisdrumond@gmail.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080

app:
  rabbitmq:
    exchanges:
      email-dead-letter: email-dlx
    queues:
      email-notification: email-queue
      email-dead-letter: email-dlq
      simulated-delay: simulated-delay-queue
    retry:
      max-attempts: 3
      initial-interval: 2000
      multiplier: 2.0
      max-interval: 10000
